<?php

namespace Tests\Feature\BankStatements;

use App\Support\BankStatements\FacilityMovementRows;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

/**
 * When a facility counts as "still has transactions" and cannot be
 * deleted.
 *
 * The guard used to accept any row carrying an amount. That held only
 * while the generated interest rows stayed empty — the database trigger
 * fills them as soon as the facility carries a balance. So a facility
 * whose statement held nothing but an imported opening balance and the
 * interest computed from it reported transactions it never had, and
 * could not be deleted at all. Three facilities on record were stuck
 * exactly that way.
 *
 * Neither of those is a movement:
 *   outstanding_balance — the amount already drawn when the facility
 *       was first entered into CashVero, typed in during setup.
 *   end_of_month — generated by the system, filled by the trigger,
 *       derived from that same opening balance.
 *
 * @see \App\Support\BankStatements\FacilityMovementRows
 */
class FacilityDeletionMovementTest extends TestCase
{
    private const COMPANY = 148;

    private const FACILITY = 7;

    /**
     * The two facility types whose deletion guard reads their
     * statements. The other two (Commercial Paper, Assignment of
     * Contract) check their limits table instead and are unaffected.
     *
     * model => [facility table, statements table, foreign key]
     */
    private const FACILITIES = [
        \App\Models\FullySecuredOverdraft::class => [
            'fully_secured_overdrafts', 'fully_secured_overdraft_bank_statements', 'fully_secured_overdraft_id',
        ],
        \App\Models\CleanOverdraft::class => [
            'clean_overdrafts', 'clean_overdraft_bank_statements', 'clean_overdraft_id',
        ],
    ];

    /** @var list<string> */
    private array $created = [];

    protected function setUp(): void
    {
        parent::setUp();

        $database = DB::connection()->getDatabaseName();
        $this->assertStringContainsString('test', $database, "Refusing to run against '{$database}'.");
    }

    protected function tearDown(): void
    {
        foreach ($this->created as $table) {
            Schema::dropIfExists($table);
        }

        parent::tearDown();
    }

    private function buildSchema(string $facilityTable, string $statementsTable, string $foreignKey): void
    {
        foreach ([$facilityTable, $statementsTable] as $table) {
            Schema::dropIfExists($table);
            $this->created[] = $table;
        }

        Schema::create($facilityTable, function ($table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('company_id');
            $table->date('contract_start_date')->nullable();
            $table->date('contract_end_date')->nullable();
            $table->decimal('limit', 18, 2)->default(0);
            $table->date('oldest_date')->nullable();
            $table->timestamps();
        });

        Schema::create($statementsTable, function ($table) use ($foreignKey) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('company_id');
            $table->unsignedBigInteger($foreignKey)->default(0);
            // NOT NULL in the real schema — an ordinary transaction
            // still carries a type, so the guard cannot rely on null.
            $table->string('type');
            $table->string('interest_type')->nullable();
            $table->date('date')->nullable();
            $table->dateTime('full_date')->nullable();
            $table->decimal('debit', 14)->default(0);
            $table->decimal('credit', 14)->default(0);
            $table->decimal('interest_amount', 14)->default(0);
            $table->timestamps();
        });

        DB::table($facilityTable)->insert([
            'id' => self::FACILITY,
            'company_id' => self::COMPANY,
            'contract_start_date' => '2026-01-01',
            'contract_end_date' => '2026-12-31',
            'limit' => 5400000,
        ]);
    }

    private function row(string $statementsTable, string $foreignKey, array $attributes): void
    {
        DB::table($statementsTable)->insert($attributes + [
            'company_id' => self::COMPANY,
            $foreignKey => self::FACILITY,
            'type' => 'withdrawal',
            'interest_type' => null,
            'date' => '2026-08-01',
            'full_date' => '2026-08-01 10:00:00',
            'debit' => 0,
            'credit' => 0,
        ]);
    }

    private function hasTransactions(string $model): bool
    {
        return $model::findOrFail(self::FACILITY)->hasAnyTransactions();
    }

    public static function facilityProvider(): array
    {
        $cases = [];

        foreach (self::FACILITIES as $model => [$facilityTable, $statementsTable, $foreignKey]) {
            $cases[class_basename($model)] = [$model, $facilityTable, $statementsTable, $foreignKey];
        }

        return $cases;
    }

    // ---------------------------------------------------------------
    // the reported case
    // ---------------------------------------------------------------

    /**
     * Exactly the shape of Fully Secured Overdraft #7 after the
     * production import: an opening balance of 3,212,979 and eleven
     * generated interest rows, five of them filled in by the trigger.
     * Zero real movement.
     *
     * @dataProvider facilityProvider
     */
    public function test_an_imported_opening_balance_and_its_interest_is_not_a_transaction(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);

        $this->row($statementsTable, $foreignKey, ['type' => 'active-limit', 'interest_type' => 'normal']);
        $this->row($statementsTable, $foreignKey, [
            'type' => 'outstanding_balance', 'interest_type' => 'normal', 'credit' => 3212979,
        ]);
        foreach (['2026-08-31' => 55456.85, '2026-09-30' => 55456.85, '2026-10-31' => 57305.41] as $date => $interest) {
            $this->row($statementsTable, $foreignKey, [
                'type' => 'interest', 'interest_type' => 'end_of_month',
                'date' => $date, 'credit' => $interest, 'interest_amount' => $interest,
            ]);
        }

        $this->assertFalse($this->hasTransactions($model),
            'A facility carrying only its opening balance and the interest derived from it must be deletable.');
    }

    // ---------------------------------------------------------------
    // each kind of row on its own
    // ---------------------------------------------------------------

    /**
     * @dataProvider facilityProvider
     */
    public function test_an_empty_facility_has_no_transactions(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);

        $this->assertFalse($this->hasTransactions($model));
    }

    /**
     * @dataProvider facilityProvider
     */
    public function test_the_opening_balance_alone_is_not_a_transaction(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);
        $this->row($statementsTable, $foreignKey, [
            'type' => 'outstanding_balance', 'interest_type' => 'normal', 'credit' => 5099068,
        ]);

        $this->assertFalse($this->hasTransactions($model));
    }

    /**
     * The trigger fills these in the moment the facility carries a
     * balance — which is what made the old guard start refusing.
     *
     * @dataProvider facilityProvider
     */
    public function test_a_generated_interest_row_is_not_a_transaction_even_when_filled(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);
        $this->row($statementsTable, $foreignKey, [
            'type' => 'interest', 'interest_type' => 'end_of_month', 'credit' => 100989.73,
        ]);
        $this->row($statementsTable, $foreignKey, [
            'type' => 'interest', 'interest_type' => 'end_of_month_final', 'credit' => 97732,
        ]);

        $this->assertFalse($this->hasTransactions($model));
    }

    /**
     * @dataProvider facilityProvider
     */
    public function test_a_zero_amount_marker_is_not_a_transaction(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);
        $this->row($statementsTable, $foreignKey, ['type' => 'active-limit', 'interest_type' => 'normal']);

        $this->assertFalse($this->hasTransactions($model));
    }

    // ---------------------------------------------------------------
    // what must still block
    // ---------------------------------------------------------------

    /**
     * The whole point of the guard: once real money moves, deletion
     * stops.
     *
     * @dataProvider facilityProvider
     */
    public function test_a_real_drawdown_still_blocks_deletion(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);
        $this->row($statementsTable, $foreignKey, [
            'type' => 'outstanding_balance', 'interest_type' => 'normal', 'credit' => 3212979,
        ]);
        $this->row($statementsTable, $foreignKey, [
            'type' => 'withdrawal', 'date' => '2026-09-15', 'credit' => 250000,
        ]);

        $this->assertTrue($this->hasTransactions($model),
            'A drawdown is a transaction whatever else is on the statement.');
    }

    /**
     * @dataProvider facilityProvider
     */
    public function test_a_settlement_on_the_debit_side_also_blocks(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);
        $this->row($statementsTable, $foreignKey, [
            'type' => 'settlement', 'date' => '2026-09-20', 'debit' => 120000,
        ]);

        $this->assertTrue($this->hasTransactions($model));
    }

    /**
     * `type` is NOT NULL in the real schema, but an interest_type of
     * NULL is normal for an ordinary movement. `NOT IN (...)` is NULL
     * for a NULL column and MySQL drops the row — which would hide
     * every real transaction. The guard has to handle that explicitly.
     *
     * @dataProvider facilityProvider
     */
    public function test_a_transaction_with_no_interest_type_is_not_swallowed_by_null(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);
        $this->row($statementsTable, $foreignKey, [
            'type' => 'withdrawal', 'interest_type' => null, 'credit' => 75000,
        ]);

        $this->assertTrue($this->hasTransactions($model),
            'A NULL interest_type must not make a real transaction invisible.');
    }

    /**
     * Interest that is NOT one of the generated month-end kinds is a
     * posting like any other.
     *
     * @dataProvider facilityProvider
     */
    public function test_interest_that_is_not_a_generated_month_end_row_still_blocks(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);
        $this->row($statementsTable, $foreignKey, [
            'type' => 'interest', 'interest_type' => 'break_interest', 'credit' => 4200,
        ]);

        $this->assertTrue($this->hasTransactions($model));
    }

    /**
     * Another facility's drawdown on the same table must not block this
     * one.
     *
     * @dataProvider facilityProvider
     */
    public function test_another_facilitys_transactions_do_not_block_this_one(
        string $model, string $facilityTable, string $statementsTable, string $foreignKey
    ): void {
        $this->buildSchema($facilityTable, $statementsTable, $foreignKey);
        DB::table($statementsTable)->insert([
            'company_id' => self::COMPANY, $foreignKey => 999,
            'type' => 'withdrawal', 'date' => '2026-09-15', 'full_date' => '2026-09-15 10:00:00',
            'debit' => 0, 'credit' => 400000,
        ]);

        $this->assertFalse($this->hasTransactions($model));
    }

    // ---------------------------------------------------------------
    // the definition lives in one place
    // ---------------------------------------------------------------

    public function test_both_guards_read_the_same_definition(): void
    {
        foreach (array_keys(self::FACILITIES) as $model) {
            $source = file_get_contents(app_path('Models/'.class_basename($model).'.php'));

            $this->assertStringContainsString('FacilityMovementRows::onlyRealMovementIn', $source,
                class_basename($model).' has its own copy of the rule instead of the shared one.');
        }
    }

    public function test_the_outstanding_balance_type_matches_what_the_writer_uses(): void
    {
        $writer = file_get_contents(app_path('Traits/HasOutstandingBreakdown.php'));

        $this->assertStringContainsString(
            "'type'=>'".FacilityMovementRows::OUTSTANDING_BALANCE_TYPE."'",
            $writer,
            'The guard excludes a row type that nothing writes — a rename would silently re-break deletion.'
        );
    }
}
